import image from '../../images/a1.jpg'
export const StudentLists = [
    {
        name: "saheed abdullateef",
        school: "transport 2",
        section: "section A",
        birthday:"2021-07-08",
        classRoom: "class room 2",
        classes: "class 1",
        email: "Sulaiman@gmail.com",
        id: '1',
        image: image,
        transport:'transport 1',
    },
    {
        name: "saheed abdullateef",
        school: "transport 2",
        section: "section A",
        birthday:"2021-07-08",
        classRoom: "class room 2",
        classes: "class 1",
        email: "Sulaiman@gmail.com",
        id: '1',
        image: image,
        transport:'transport 1',
    },
    {
        name: "saheed abdullateef",
        school: "transport 2",
        section: "section A",
        birthday:"2021-07-08",
        classRoom: "class room 2",
        classes: "class 1",
        email: "Sulaiman@gmail.com",
        id: '1',
        image: image,
        transport:'transport 1',
    },
    {
        name: "saheed abdullateef",
        school: "transport 2",
        section: "section A",
        birthday:"2021-07-08",
        classRoom: "class room 2",
        classes: "class 1",
        email: "Sulaiman@gmail.com",
        id: '1',
        image: image,
        transport:'transport 1',
    },
    {
        name: "saheed abdullateef",
        school: "transport 2",
        section: "section A",
        birthday:"2021-07-08",
        classRoom: "class room 2",
        classes: "class 1",
        email: "Sulaiman@gmail.com",
        id: '1',
        image: image,
        transport:'transport 1',
    },
    {
        name: "saheed abdullateef",
        school: "transport 2",
        section: "section A",
        birthday:"2021-07-08",
        classRoom: "class room 2",
        classes: "class 1",
        email: "Sulaiman@gmail.com",
        id: '1',
        image: image,
        transport:'transport 1',
    },
    {
        name: "saheed abdullateef",
        school: "transport 2",
        section: "section A",
        birthday:"2021-07-08",
        classRoom: "class room 2",
        classes: "class 1",
        email: "Sulaiman@gmail.com",
        id: '1',
        image: image,
        transport:'transport 1',
    },
    {
        name: "saheed abdullateef",
        school: "transport 2",
        section: "section B",
        birthday:"2021-07-08",
        classRoom: "class room 2",
        classes: "class 1",
        email: "Sulaiman@gmail.com",
        id: '1',
        image: image,
        transport:'transport 1',
    },
{
    name: "saheed abdullateef",
    school: "transport 2",
    section: "section B",
    birthday:"2021-07-08",
    classRoom: "class room 2",
    classes: "class 1",
    email: "Sulaiman@gmail.com",
    id: '2',
    image: image,
    transport:'transport 1',
},

{
    name: "saheed abdullateef",
    school: "transport 2",
    section: "section B",
    birthday:"2021-07-08",
    classRoom: "class room 2",
    classes: "class 1",
    email: "Sulaiman@gmail.com",
    id: '3',
    image: image,
    transport:'transport 1',
},

{
    name: "saheed abdullateef",
    school: "transport 2",
    section: "section B",
    birthday:"2021-07-08",
    classRoom: "class room 2",
    classes: "class 1",
    email: "Sulaiman@gmail.com",
    id: '4',
    image: image,
    transport:'transport 1',
},

{
    name: "saheed abdullateef",
    school: "transport 2",
    section: "section B",
    birthday:"2021-07-08",
    classRoom: "class room 2",
    classes: "class 1",
    email: "Sulaiman@gmail.com",
    id: '5',
    image: image,
    transport:'transport 1',
},

{
    name: "saheed abdullateef",
    school: "transport 2",
    section: "section B",
    birthday:"2021-07-08",
    classRoom: "class room 2",
    classes: "class 1",
    email: "Sulaiman@gmail.com",
    id: '6',
    image: image,
    transport:'transport 1',
},

{
    name: "saheed abdullateef",
    school: "transport 2",
    section: "section B",
    birthday:"2021-07-08",
    classRoom: "class room 2",
    classes: "class 1",
    email: "Sulaiman@gmail.com",
    id: '7',
    image: image,
    transport:'transport 1',
},

{
    name: "saheed abdullateef",
    school: "transport 2",
    section: "section B",
    birthday:"2021-07-08",
    classRoom: "class room 2",
    classes: "class 1",
    email: "Sulaiman@gmail.com",
    id: '8',
    image: image,
    transport:'transport 1',
},

{
    name: "saheed abdullateef",
    school: "transport 2",
    section: "section A",
    birthday:"2021-07-08",
    classRoom: "class room 2",
    classes: "class 2",
    email: "Sulaiman@gmail.com",
    id: '9',
    image: image,
    transport:'transport 1',
},
{
    name: "saheed abdullateef",
    school: "transport 2",
    section: "section A",
    birthday:"2021-07-08",
    classRoom: "class room 2",
    classes: "class 2",
    email: "Sulaiman@gmail.com",
    id: '10',
    image: image,
    transport:'transport 1',
},
{
    name: "saheed abdullateef",
    school: "transport 2",
    section: "section A",
    birthday:"2021-07-08",
    classRoom: "class room 2",
    classes: "class 2",
    email: "Sulaiman@gmail.com",
    id: '11',
    image: image,
    transport:'transport 1',
},
{
    name: "saheed abdullateef",
    school: "transport 2",
    section: "section A",
    birthday:"2021-07-08",
    classRoom: "class room 2",
    classes: "class 2",
    email: "Sulaiman@gmail.com",
    id: '12',
    image: image,
    transport:'transport 1',
},
{
    name: "saheed abdullateef",
    school: "transport 2",
    section: "section A",
    birthday:"2021-07-08",
    classRoom: "class room 2",
    classes: "class 2",
    email: "Sulaiman@gmail.com",
    id: '13',
    image: image,
    transport:'transport 1',
},

{
    name: "saheed abdullateef",
    school: "transport 2",
    section: "section B",
    birthday:"2021-07-08",
    classRoom: "class room 2",
    classes: "class 2",
    email: "Sulaiman@gmail.com",
    id: '14',
    image: image,
    transport:'transport 1',
},

{
    name: "saheed abdullateef",
    school: "transport 2",
    section: "section B",
    birthday:"2021-07-08",
    classRoom: "class room 2",
    classes: "class 2",
    email: "Sulaiman@gmail.com",
    id: '15',
    image: image,
    transport:'transport 1',
},

{
    name: "saheed abdullateef",
    school: "transport 2",
    section: "section B",
    birthday:"2021-07-08",
    classRoom: "class room 2",
    classes: "class 2",
    email: "Sulaiman@gmail.com",
    id: '16',
    image: image,
    transport:'transport 1',
},

{
    name: "saheed abdullateef",
    school: "transport 2",
    section: "section B",
    birthday:"2021-07-08",
    classRoom: "class room 2",
    classes: "class 2",
    email: "Sulaiman@gmail.com",
    id: '17',
    image: image,
    transport:'transport 1',
},

{
    name: "saheed abdullateef",
    school: "transport 2",
    section: "section B",
    birthday:"2021-07-08",
    classRoom: "class room 2",
    classes: "class 2",
    email: "Sulaiman@gmail.com",
    id: '18',
    image: image,
    transport:'transport 1',
},

{
    name: "saheed abdullateef",
    school: "transport 2",
    section: "section B",
    birthday:"2021-07-08",
    classRoom: "class room 2",
    classes: "class 2",
    email: "Sulaiman@gmail.com",
    id: '19',
    image: image,
    transport:'transport 1',
},

{
    name: "saheed abdullateef",
    school: "transport 2",
    section: "section B",
    birthday:"2021-07-08",
    classRoom: "class room 2",
    classes: "class 2",
    email: "Sulaiman@gmail.com",
    id: '20',
    image: image,
    transport:'transport 1',
},

{
    name: "saheed abdullateef",
    school: "transport 2",
    section: "section C",
    birthday:"2021-07-08",
    classRoom: "class room 2",
    classes: "class 2",
    email: "Sulaiman@gmail.com",
    id: '21',
    image: image,
    transport:'transport 1',
},


{
    name: "saheed abdullateef",
    school: "transport 2",
    section: "section C",
    birthday:"2021-07-08",
    classRoom: "class room 2",
    classes: "class 2",
    email: "Sulaiman@gmail.com",
    id: '22',
    image: image,
    transport:'transport 1',
},

{
    name: "saheed abdullateef",
    school: "transport 2",
    section: "section C",
    birthday:"2021-07-08",
    classRoom: "class room 2",
    classes: "class 2",
    email: "Sulaiman@gmail.com",
    id: '23',
    image: image,
    transport:'transport 1',
},

{
    name: "saheed abdullateef",
    school: "transport 2",
    section: "section C",
    birthday:"2021-07-08",
    classRoom: "class room 2",
    classes: "class 2",
    email: "Sulaiman@gmail.com",
    id: '24',
    image: image,
    transport:'transport 1',
},

{
    name: "saheed abdullateef",
    school: "transport 2",
    section: "section C",
    birthday:"2021-07-08",
    classRoom: "class room 2",
    classes: "class 2",
    email: "Sulaiman@gmail.com",
    id: '25',
    image: image,
    transport:'transport 1',
},

{
    name: "saheed abdullateef",
    school: "transport 2",
    section: "section C",
    birthday:"2021-07-08",
    classRoom: "class room 2",
    classes: "class 2",
    email: "Sulaiman@gmail.com",
    id: '26',
    image: image,
    transport:'transport 1',
},

{
    name: "saheed abdullateef",
    school: "transport 2",
    section: "section C",
    birthday:"2021-07-08",
    classRoom: "class room 2",
    classes: "class 1",
    email: "Sulaiman@gmail.com",
    id: '27',
    image: image,
    transport:'transport 1',
},

{
    name: "saheed abdullateef",
    school: "transport 2",
    section: "section C",
    birthday:"2021-07-08",
    classRoom: "class room 2",
    classes: "class 1",
    email: "Sulaiman@gmail.com",
    id: '28',
    image: image,
    transport:'transport 1',
},

{
    name: "saheed abdullateef",
    school: "transport 2",
    section: "section C",
    birthday:"2021-07-08",
    classRoom: "class room 2",
    classes: "class 1",
    email: "Sulaiman@gmail.com",
    id: '29',
    image: image,
    transport:'transport 1',
},

{
    name: "saheed abdullateef",
    school: "transport 2",
    section: "section C",
    birthday:"2021-07-08",
    classRoom: "class room 2",
    classes: "class 1",
    email: "Sulaiman@gmail.com",
    id: '30',
    image: image,
    transport:'transport 1',
},

{
    name: "saheed abdullateef",
    school: "transport 2",
    section: "section C",
    birthday:"2021-07-08",
    classRoom: "class room 2",
    classes: "class 1",
    email: "Sulaiman@gmail.com",
    id: '31',
    image: image,
    transport:'transport 1',
},

{
    name: "saheed abdullateef",
    school: "transport 2",
    section: "section C",
    birthday:"2021-07-08",
    classRoom: "class room 2",
    classes: "class 1",
    email: "Sulaiman@gmail.com",
    id: '32',
    image: image,
    transport:'transport 1',
},
]