import image from '../../../images/a1.jpg'
export const StudentLists = [

{
name: "saheed abdullateef",
school: "transport 2",
section: "section B",
birthday:"2021-07-08",
classRoom: "class room 2",
classes: "class 1",
email: "Sulaiman@gmail.com",
id: '1',
image: image,
transport:'transport 1',
},
{
    name: "saheed abdullateef",
    school: "transport 2",
    section: "section B",
    birthday:"2021-07-08",
    classRoom: "class room 2",
    classes: "class 1",
    email: "Sulaiman@gmail.com",
    id: '2',
    image: image,
    transport:'transport 1',
},

{
    name: "saheed abdullateef",
    school: "transport 2",
    section: "section B",
    birthday:"2021-07-08",
    classRoom: "class room 2",
    classes: "class 1",
    email: "Sulaiman@gmail.com",
    id: '3',
    image: image,
    transport:'transport 1',
},

{
    name: "saheed abdullateef",
    school: "transport 2",
    section: "section B",
    birthday:"2021-07-08",
    classRoom: "class room 2",
    classes: "class 1",
    email: "Sulaiman@gmail.com",
    id: '4',
    image: image,
    transport:'transport 1',
},

{
    name: "saheed abdullateef",
    school: "transport 2",
    section: "section B",
    birthday:"2021-07-08",
    classRoom: "class room 2",
    classes: "class 1",
    email: "Sulaiman@gmail.com",
    id: '5',
    image: image,
    transport:'transport 1',
},

{
    name: "saheed abdullateef",
    school: "transport 2",
    section: "section B",
    birthday:"2021-07-08",
    classRoom: "class room 2",
    classes: "class 1",
    email: "Sulaiman@gmail.com",
    id: '6',
    image: image,
    transport:'transport 1',
},

{
    name: "saheed abdullateef",
    school: "transport 2",
    section: "section B",
    birthday:"2021-07-08",
    classRoom: "class room 2",
    classes: "class 1",
    email: "Sulaiman@gmail.com",
    id: '7',
    image: image,
    transport:'transport 1',
},

{
    name: "saheed abdullateef",
    school: "transport 2",
    section: "section B",
    birthday:"2021-07-08",
    classRoom: "class room 2",
    classes: "class 1",
    email: "Sulaiman@gmail.com",
    id: '8',
    image: image,
    transport:'transport 1',
},

{
    name: "saheed abdullateef",
    school: "transport 2",
    section: "section B",
    birthday:"2021-07-08",
    classRoom: "class room 2",
    classes: "class 1",
    email: "Sulaiman@gmail.com",
    id: '9',
    image: image,
    transport:'transport 1',
},

{
    name: "saheed abdullateef",
    school: "transport 2",
    section: "section B",
    birthday:"2021-07-08",
    classRoom: "class room 2",
    classes: "class 1",
    email: "Sulaiman@gmail.com",
    id: '10',
    image: image,
    transport:'transport 1',
},

{
    name: "saheed abdullateef",
    school: "transport 2",
    section: "section B",
    birthday:"2021-07-08",
    classRoom: "class room 2",
    classes: "class 1",
    email: "Sulaiman@gmail.com",
    id: '11',
    image: image,
    transport:'transport 1',
},
]